FROM ubuntu:18.04

ARG ruby
ENV RUBY=$ruby

ENV LANG C.UTF-8
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get -y install apt-utils libmysqlclient-dev libpq-dev libsqlite3-dev cmake glib2.0
RUN apt-get -y install nodejs
RUN apt-get -y install npm

COPY ./pakyow-master /pakyow

WORKDIR /pakyow

# Fixes "mesg: ttyname failed: Inappropriate ioctl for device" warning.
#
RUN cp /etc/profile /root/.profile

ENTRYPOINT ["/bin/bash", "-l", "-c"]
