name: Build CI Docker Images

on: repository_dispatch

jobs:
  build-ruby:
    name: Build Ruby ${{ matrix.ruby }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby:
          - 2.5.7
          - 2.6.5

    steps:
    - uses: actions/checkout@master

    - name: Download pakyow
      run: |
        cd ci
        wget https://github.com/pakyow/pakyow/archive/master.zip
        unzip master.zip

    - name: Build the Docker container image
      run: |
        cd ci
        docker build --build-arg ruby=${{ matrix.ruby }} -t pakyow/ci-ruby-${{ matrix.ruby }}:latest .

    - name: Push the image to docker hub
      run: |
        docker login -u ${DOCKER_HUB_USER} -p "${DOCKER_HUB_TOKEN}"
        docker push pakyow/ci-ruby-${{ matrix.ruby }}:latest

      env:
        DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}

  build-ruby-head:
    name: Build Ruby Head
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Download pakyow
      run: |
        cd ci
        wget https://github.com/pakyow/pakyow/archive/master.zip
        unzip master.zip

    - name: Build the Docker container image
      run: |
        cd ci
        docker build --build-arg ruby=ruby-head -t pakyow/ci-ruby-head:latest .

    - name: Push the image to docker hub
      run: |
        docker login -u ${DOCKER_HUB_USER} -p "${DOCKER_HUB_TOKEN}"
        docker push pakyow/ci-ruby-head:latest

      env:
        DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
