name: Build CI Docker Images

on: repository_dispatch

jobs:
  build-ruby-2_6_5:
    name: Build Ruby 2.6.5
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Download pakyow
      run: |
        cd ci
        wget https://github.com/pakyow/pakyow/archive/master.zip
        unzip master.zip

    - name: Build the Docker container image
      run: |
        cd ci
        docker build --build-arg ruby=2.6.5 -t pakyow/ci-ruby-2.6.5:latest .

    - name: Push the image to docker hub
      run: |
        docker login -u ${DOCKER_HUB_USER} -p "${DOCKER_HUB_TOKEN}"
        docker push pakyow/ci-ruby-2.6.5:latest

      env:
        DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
