name: Build CI Docker Images

on: repository_dispatch

jobs:
  build-ruby-2_6_5:
    name: Build Ruby 2.6.5
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@master

    - name: Clone pakyow
      run: |
        git clone git@github.com:pakyow/pakyow.git
        ls
