name: Build CI Docker Images

on: repository_dispatch

jobs:
  build-ruby-2_6_5:
    name: Build Ruby 2.6.5
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Download pakyow
      run: |
        wget https://github.com/pakyow/pakyow/archive/master.zip
        unzip master.zip

    - name: Build the Docker container image
      run: |
        docker build --build-arg ruby=2.6.5 -t pakyow/ci-ruby-2.6.5:latest ci
